In [3]:
import numpy as np
import cv2
from scipy.ndimage import convolve

In [12]:
def canny_detector(img, highThresholdRatio=0.15, lowThresholdRatio=0.05, sigma=1.4):
    """convert image to grayscale"""
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    """Noise reduction"""
    img = cv2.GaussianBlur(img, (5, 5), sigma)

    """Calculate the gradients"""
    sobel_kx = np.array([[-1, 0, 1],
                         [-2, 0, 2],
                         [-1, 0, 1]], np.float32)
    sobel_ky = np.array([[1, 2, 1],
                         [0, 0, 0],
                         [-1, -2, -1]], np.float32)

    gx = cv2.filter2D(img, -1, sobel_kx)
    gy = cv2.filter2D(img, -1, sobel_ky)

    """Calculate magnitude and angle"""
    g = np.power((gx**2 + gy**2), 1/2)
    theta = np.arctan(gy/gx)

    """Non-maximum supression"""
    M, N = g.shape
    Z = np.zeros((M,N), dtype=np.int32)
    angle = theta * 180. / np.pi
    angle[angle < 0] += 180


    for i in range(1, M-1):
        for j in range(1, N-1):
            q = 255
            r = 255
            #angle 0
            if 0 <= angle[i,j] < 22.5 or 157.5 <= angle[i,j] <= 180:
                q = g[i, j+1]
                r = g[i, j-1]
            #angle 45
            elif 22.5 <= angle[i, j] < 67.5:
                q = g[i+1, j-1]
                r = g[i-1, j+1]
            #angle 90
            elif 67.5 <= angle[i, j] < 112.5:
                q = g[i+1, j]
                r = g[i-1, j]
            #angle 135
            elif 112.5 <= angle[i, j] < 157.5:
                q = img[i-1, j-1]
                r = img[i+1, j+1]
            if g[i,j] >= q and g[i, j] >= r:
                Z[i, j] = g[i, j]
            else:
                Z[i, j] = 0

        """Threshold"""
        highThreshold = img.max() * highThresholdRatio
        lowThreshold = highThreshold * lowThresholdRatio

In [13]:
image = cv2.imread('2.jpg')
canny_img = canny_detector(image)

[[-1.  0.  1.]
 [-2.  0.  2.]
 [-1.  0.  1.]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
square - 10.0


C:\Users\Asus\AppData\Local\Temp\ipykernel_97868\841634565.py:21: RuntimeWarning: divide by zero encountered in true_divide
  theta = np.arctan(gy/gx)
C:\Users\Asus\AppData\Local\Temp\ipykernel_97868\841634565.py:21: RuntimeWarning: invalid value encountered in true_divide
  theta = np.arctan(gy/gx)
